"""Banque de Reels — livre 2 de Sabine Mercier (anxiété).

Source : « 101 vérités que ton anxiété essaie de te dire », Sabine Mercier.
Chaque entrée : n (numéro de la vérité, None = « 101 VÉRITÉS »), hook (\n = saut de ligne forcé),
texto (4 paragraphes lus par la voix et affichés un par un), leyenda (légende Instagram, une phrase + emoji).
*mot* = écrit en corail manuscrit (un dans le hook, un dans le dernier paragraphe).
Ordre de la liste = ordre de publication. Reels 4, 8, 12… : se terminent sur la photo du livre (légende avec lien).
Reels 2, 6, 10… : légende qui invite à partager.
Règles : tournures neutres (aucun adjectif accordé à « tu »), pas de « guérir », pas de chiffres invérifiables.
"""

FRASES = [
    # 1
    dict(n=1, hook="Ton anxiété n'est pas\nune faiblesse.\nC'est une alarme\ntrop *sensible*.",
         texto=["Ton cerveau est si doué pour repérer les menaces qu'il en voit même là où il n'y en a pas.",
                "C'est comme un détecteur de fumée qui se déclenche dès que tu fais griller du pain.",
                "Le problème n'est pas le détecteur. C'est son réglage.",
                "Tu n'es pas quelqu'un de défaillant. Tu es quelqu'un de *suréquipé.*"],
         leyenda="Tu n'as rien de défaillant, ton alarme est juste réglée trop fort. 🔔"),
    # 2
    dict(n=67, hook="Éviter ce qui te fait\npeur te soulage.\nPuis la peur *grandit*.",
         texto=["Chaque fois que tu fuis une situation qui t'angoisse, tu confirmes à ton cerveau qu'elle était dangereuse.",
                "Le soulagement est immédiat. Mais la peur, elle, se renforce.",
                "Affronter la peur par petites doses, pas à pas, apprend à ton alarme à se calmer.",
                "Éviter, c'est renforcer. Avancer doucement, c'est *désamorcer.*"],
         leyenda="Un tout petit pas vers ce qui te fait peur vaut mieux qu'un grand détour. 👣"),
    # 3
    dict(n=29, hook="Le futur est une dette\nque tu paies avant\nd'avoir reçu la *facture*.",
         texto=["L'anxiété d'anticipation te fait vivre aujourd'hui la douleur de demain.",
                "Mais tu n'as pas encore les ressources de demain pour régler le problème de demain.",
                "Tu ne peux utiliser que tes forces de maintenant.",
                "Alors reviens à ce que tu peux toucher, voir et *entendre.*"],
         leyenda="Demain arrivera avec ses propres ressources. ⏳"),
    # 4
    dict(n=None, hook="Ton anxiété ?\nUn gardien de phare\nqui voit des naufrages\n*partout*.",
         texto=["Un jour, une part de toi a eu très peur. Et elle a décidé de ne plus jamais baisser la garde.",
                "Depuis, elle scrute l'horizon sans dormir, et chaque vague lui paraît une tempête.",
                "Elle n'est pas méchante. Elle est épuisée.",
                "Elle n'a pas besoin qu'on la combatte. Elle a besoin qu'on fasse la *paix.*"],
         leyenda="On ne fait pas la guerre à une part de soi qui a eu peur. 🌅"),
    # 5
    dict(n=25, hook="Tu n'arrives pas\nà dormir ? Ton cerveau\nrefuse de baisser\nla *garde*.",
         texto=["Dormir, c'est l'acte de vulnérabilité ultime.",
                "Si ton cerveau croit que le monde est hostile, il t'empêche de sombrer, pour rester prêt à réagir.",
                "Et plus tu te bats contre l'insomnie, plus la tension monte.",
                "Accepte de ne pas dormir, et contente-toi de reposer ton corps. C'est souvent ce qui ouvre la porte au *sommeil.*"],
         leyenda="Ce soir, ne cherche pas à dormir, cherche seulement à te reposer. 🌙"),
    # 6
    dict(n=20, hook="Ton cœur s'accélère ?\nIl ne lâche pas.\nIl se *prépare*.",
         texto=["Les palpitations comptent parmi les signes les plus effrayants de l'anxiété.",
                "Pourtant, ton cœur fait exactement son travail : il pompe plus de sang pour donner de l'énergie à tes muscles.",
                "Il ne s'emballe pas parce qu'il est instable. Il se mobilise pour te protéger.",
                "Remercie-le pour son zèle, et dis-lui que pour l'instant, aucun acte *héroïque* n'est nécessaire."],
         leyenda="Ton cœur est de ton côté, même quand il en fait trop. ❤️"),
    # 7
    dict(n=40, hook="Te parler durement\nne te motive pas.\nÇa t'*épuise*.",
         texto=["Tu te critiques en pensant que ça t'empêchera d'échouer.",
                "En réalité, chaque reproche envoie un signal de menace à ton cerveau.",
                "Ton système nerveux ne peut pas se sentir en sécurité si ton plus grand juge, c'est toi.",
                "La douceur n'est pas de la faiblesse. C'est un *outil.*"],
         leyenda="Parle-toi comme tu parlerais à quelqu'un que tu aimes. 🤍"),
    # 8
    dict(n=101, hook="Ton anxiété s'apaisera\nle jour où tu lui diras\n*merci*.",
         texto=["« Merci d'avoir essayé de me protéger, maladroitement, pendant toutes ces années. »",
                "« Je comprends ton message. Mais maintenant, je prends le relais. »",
                "« Je suis en sécurité. »",
                "Ce n'est pas une défaite. C'est l'acte final de *souveraineté.*"],
         leyenda="Et si tu essayais de le lui dire, rien qu'une fois ? 🙏"),
    # 9
    dict(n=22, hook="Épuisement sans avoir\nrien fait ? Ton alarme\na tourné toute\nla *journée*.",
         texto=["Rester aux aguets du matin au soir consomme une énergie énorme, mentale et physique.",
                "Ton système nerveux passe ses journées à scanner l'horizon à la recherche de menaces.",
                "Ce n'est pas parce que personne ne le voit que ça ne coûte rien.",
                "Le repos n'est pas une récompense. C'est une nécessité *biologique.*"],
         leyenda="Tu as le droit de te reposer avant d'avoir « mérité » ton repos. 🛋️"),
    # 10
    dict(n=38, hook="Une pensée anxieuse\nn'est pas une preuve.\nC'est une *hypothèse*.",
         texto=["La plupart de tes pensées sont automatiques, répétitives, et jamais vérifiées.",
                "Ton cerveau les produit comme un bruit de fond, et ton anxiété les prend pour des faits.",
                "Tu peux apprendre à ajouter une petite phrase : « Ceci est une pensée, pas un fait. »",
                "Ce n'est pas un jeu de mots. C'est un acte de *régulation.*"],
         leyenda="Ce que tu penses n'est pas forcément ce qui est vrai. 🧠"),
    # 11
    dict(n=8, hook="Ton cerveau ne fait\npas toujours la différence\nentre réel et *imaginé*.",
         texto=["Quand tu imagines une catastrophe ou une scène humiliante, ton corps libère les mêmes hormones de stress que si elle avait vraiment lieu.",
                "Ton imagination est un outil puissant. Mais tournée vers la peur, elle devient une prison.",
                "Pour en sortir, reviens à tes cinq sens : ce que tu vois, entends et touches, maintenant.",
                "C'est comme ça que tu rappelles à ton cerveau la *réalité.*"],
         leyenda="Ce que tu imagines n'est pas en train d'arriver. 🌿"),
    # 12
    dict(n=94, hook="Tu es le ciel.\nTon anxiété n'est qu'un\nphénomène *météo*.",
         texto=["Regarde tes pensées et tes sensations comme des nuages qui passent.",
                "Certains sont sombres, orageux, menaçants.",
                "Mais aucun nuage n'abîme le ciel derrière lui.",
                "Tu es l'espace qui accueille l'orage. Pas l'orage *lui-même.*"],
         leyenda="Même le plus gros orage finit par passer. ☁️"),
    # 13
    dict(n=12, hook="Tu scrutes sans cesse\nle regard des autres ?\nC'est une *cicatrice*.",
         texto=["Ton anxiété sociale n'est pas un trait de caractère. Ce n'est pas de la timidité.",
                "Un jour, quelqu'un t'a fait sentir que tu n'étais pas à ta place, ou que tu étais « trop ».",
                "Depuis, ton anxiété essaie de t'éviter de revivre cette douleur, en te poussant à prendre le moins de place possible.",
                "Comprendre d'où vient cette peur, c'est déjà commencer à t'en *détacher.*"],
         leyenda="Ce n'est pas toi qui es « trop », c'est une vieille blessure qui parle encore. 🩹"),
    # 14
    dict(n=56, hook="« Et si… » est\nla phrase préférée\nde ton *anxiété*.",
         texto=["Elle t'emmène dans des futurs qui n'existent pas, pour te faire vivre des catastrophes imaginaires.",
                "Ton cerveau croit qu'en explorant tous les scénarios, il te protège. En réalité, il t'épuise.",
                "Remplace le « Et si… » par : « On verra bien le moment venu. »",
                "Et fais confiance à la personne que tu seras demain pour régler les problèmes de *demain.*"],
         leyenda="La personne que tu seras demain aura ce qu'il faut. 🌤️"),
    # 15
    dict(n=17, hook="Tu n'es pas fragile.\nTu as appris à tout\n*anticiper*.",
         texto=["« Fragile », c'est l'étiquette qu'on colle quand on ne comprend pas ton intensité.",
                "En vérité, tu navigues chaque jour dans un océan d'alertes que les autres ne voient même pas.",
                "Ton système est simplement réglé sur « survie maximale ».",
                "Tu n'as pas besoin de plus de force. Tu as besoin de plus de *sécurité.*"],
         leyenda="Ce qu'on appelle fragilité, c'est souvent une résistance que personne ne voit. 🌊"),
    # 16
    dict(n=None, hook="Ne lis pas tout\nd'un coup. Lis-en une\nquand le souffle\nte *manque*.",
         texto=["Ce livre n'est pas un manuel de combat. C'est un traité de paix.",
                "101 vérités courtes, à lire dans l'ordre ou au hasard.",
                "Une quand tu te sens « trop ». Une quand ton cœur bat ce rythme que tu connais par cœur.",
                "Laisse chaque vérité *infuser.*"],
         leyenda="Celle dont tu as besoin ce soir t'attend peut-être à la page suivante. 📖"),
    # 17
    dict(n=37, hook="Ce n'est pas ta première\npeur qui t'enferme.\nC'est la *seconde*.",
         texto=["La première peur est instinctive : ton cœur bat vite.",
                "La seconde, c'est ce que ton esprit en dit : « Pourquoi il fait ça ? Il se passe quelque chose de grave. »",
                "C'est cette seconde peur qui crée la spirale.",
                "Observe la sensation sans y ajouter d'histoire terrifiante. Elle finit toujours par *redescendre.*"],
         leyenda="La sensation passe, c'est l'histoire qu'on lui raconte qui la retient. 🌀"),
    # 18
    dict(n=3, hook="Tu t'inquiètes\nparce que tu tiens\nà quelque chose.\nTrès *fort*.",
         texto=["L'anxiété est le revers de ton amour. Si tout t'était égal, tu ne t'inquiéterais pas.",
                "Derrière chaque peur, il y a quelque chose qui compte : ta santé, tes proches, ton avenir.",
                "L'inquiétude, c'est de l'engagement mal canalisé.",
                "Regarde l'amour derrière la peur, et elle devient moins *monstrueuse.*"],
         leyenda="Ce qui t'inquiète en dit long sur ce que tu aimes. 💛"),
    # 19
    dict(n=32, hook="Inspire 4 secondes.\nExpire 6 secondes.\nRecommence. C'est de\nla *biologie*.",
         texto=["Une respiration lente et profonde, avec une expiration plus longue que l'inspiration, aide ton corps à passer du mode combat au mode repos.",
                "Ce n'est pas une formule magique. C'est une compétence.",
                "Plus tu t'y entraînes quand tout va bien, mieux elle répondra quand l'orage éclatera.",
                "Pratique-la jusqu'à ce qu'elle devienne un *réflexe.*"],
         leyenda="Essaie maintenant, pendant que tu lis ces mots. 🌬️"),
    # 20
    dict(n=65, hook="Ton anxiété n'est pas\nun état à vie.\nC'est une *phase*.",
         texto=["Ce n'est pas une identité gravée dans le marbre. C'est un état que tu traverses.",
                "Des millions de personnes ont appris à sortir de l'anxiété chronique.",
                "Rien ne dit que tu ne seras pas l'une d'elles.",
                "Donne-toi du *temps.*"],
         leyenda="Ce que tu vis aujourd'hui n'est pas ce que tu vivras toujours. 🌱"),
    # 21
    dict(n=50, hook="Tu veux une certitude\nà 100 % ? Elle\nn'existe *pas*.",
         texto=["Savoir à coup sûr que tu n'es pas malade, que tout ira bien, que les autres tiennent à toi…",
                "Ce besoin de certitude absolue est le carburant de l'obsession.",
                "La paix ne vient pas de la réponse. Elle vient de ta capacité à ne pas savoir.",
                "L'incertitude n'est pas un danger. C'est le terreau de ta *liberté.*"],
         leyenda="« Je ne sais pas » est une réponse que tu peux apprendre à supporter. 🍃"),
    # 22
    dict(n=14, hook="Ton besoin\nd'approbation est\nune très vieille\n*stratégie*.",
         texto=["Pendant des millénaires, être exclu du groupe menaçait la survie.",
                "Ton cerveau a gardé ce programme : « Si on ne m'approuve pas, je suis en danger. »",
                "Aujourd'hui, tu peux survivre à un désaccord. Ou à un froncement de sourcils.",
                "Tu peux apprendre à rassurer cet instinct, en te donnant ta propre *approbation.*"],
         leyenda="Un désaccord n'est pas un danger, c'est juste un désaccord. 🤝"),
    # 23
    dict(n=43, hook="Se sentir en danger\nn'est pas être\nen *danger*.",
         texto=["« Je me sens mal, donc quelque chose de grave va arriver » : c'est une erreur de logique.",
                "Ce que tu ressens, ce n'est pas ton futur. C'est l'état de ton système nerveux, maintenant.",
                "Une alarme qui hurle ne prouve pas qu'il y a un incendie. Seulement qu'elle est sensible.",
                "Écoute le message, mais vérifie sa *fiabilité.*"],
         leyenda="Tes émotions t'informent, elles ne prédisent pas l'avenir. 📡"),
    # 24
    dict(n=35, hook="Ton cerveau préfère\nimaginer le pire\nplutôt qu'être *surpris*.",
         texto=["Pour lui, une mauvaise certitude est plus rassurante qu'une absence de réponse.",
                "En imaginant le pire, il a l'impression de se préparer au choc.",
                "Mais s'inquiéter ne change rien à demain. Ça prend juste ta force d'aujourd'hui.",
                "Supporter le « je ne sais pas », c'est le plus grand acte de *courage.*"],
         leyenda="Ton cerveau croit te préparer, en réalité il t'épuise d'avance. 🌫️"),
    # 25
    dict(n=26, hook="Mâchoire serrée,\népaules remontées ?\nTon corps attend\nun *choc*.",
         texto=["Ton corps se contracte pour amortir un impact émotionnel qu'il imagine déjà.",
                "C'est une armure de tension.",
                "Prends un instant pour parcourir ton corps, et relâcher une à une les zones serrées.",
                "C'est une manière de lui dire que l'impact n'aura pas lieu *aujourd'hui.*"],
         leyenda="Desserre la mâchoire et baisse les épaules, là, maintenant. 🫶"),
    # 26
    dict(n=88, hook="Une mauvaise journée\naprès plusieurs bonnes ?\nCe n'est pas un *échec*.",
         texto=["Certains jours, tout semble plus léger.",
                "D'autres, l'anxiété revient en force, et tu as l'impression de repartir à zéro.",
                "Ton cerveau désapprend une habitude de plusieurs années. Les rechutes font partie du chemin.",
                "Tu n'es pas en train de reculer. Tu es en train d'*apprendre.*"],
         leyenda="Le chemin n'est jamais une ligne droite, et il avance quand même. 🛤️"),
    # 27
    dict(n=61, hook="Ton intuition murmure.\nTon anxiété *hurle*.",
         texto=["Ce n'est pas toujours facile de les distinguer.",
                "L'anxiété est bruyante, répétitive, et te pousse à l'urgence.",
                "L'intuition est calme, immédiate, et n'a pas besoin de te faire peur pour te convaincre.",
                "Si le message te met une pression terrible, c'est ton anxiété. Si c'est une certitude tranquille, c'est ton *intuition.*"],
         leyenda="La voix qui t'aide n'a jamais besoin de crier. 🤫"),
    # 28
    dict(n=2, hook="Ton anxiété ? Un garde\ndu corps qui patrouille\nalors que la guerre\nest *finie*.",
         texto=["Il y a sans doute eu une période de ta vie où rester aux aguets était nécessaire.",
                "Ton hypervigilance est une réponse logique à un passé où tout était imprévisible.",
                "Aujourd'hui, le danger est peut-être passé. Mais ton garde du corps ne le sait pas encore.",
                "Remercie-le d'avoir veillé sur toi. Puis dis-lui qu'il a le droit de se *reposer.*"],
         leyenda="Il a veillé sur toi longtemps, il peut enfin poser les armes. 🕊️"),
    # 29
    dict(n=55, hook="Vérifier te calme\ndeux minutes.\nPuis le doute\n*revient*.",
         texto=["Relire un message, chercher un symptôme, contrôler ton travail encore une fois…",
                "Chaque vérification calme l'anxiété un instant, puis la renforce pour des heures.",
                "C'est un cercle : plus tu vérifies, plus tu as besoin de vérifier.",
                "Le changement commence le jour où tu choisis de ne pas vérifier, et de laisser l'inconfort s'éteindre de *lui-même.*"],
         leyenda="Le doute ne part pas quand on vérifie, il part quand on le laisse passer. ✋"),
    # 30
    dict(n=73, hook="Décevoir quelqu'un\nest parfois le seul\nmoyen de te *respecter*.",
         texto=["Ton anxiété explose quand tu dis « oui » alors que tout ton corps crie « non ».",
                "Poser une limite, c'est accepter le risque de décevoir.",
                "Mais mieux vaut décevoir quelqu'un d'autre que te trahir toi-même.",
                "Tes limites ne sont pas des murs contre les autres. Ce sont les frontières de ta *paix.*"],
         leyenda="Ton « non » protège quelque chose de précieux : toi. 🚪"),
    # 31
    dict(n=31, hook="Ton anxiété ne se calme\npas toujours par la tête.\nParfois, par le *corps*.",
         texto=["Les pensées ne suffisent pas toujours à apaiser une alarme lancée.",
                "Le toucher, un mouvement doux, le son d'une voix envoient des signaux de sécurité directement à ton système nerveux.",
                "Ils passent par le bas, sans attendre que ta tête soit convaincue.",
                "Parfois, le corps se rassure là où dix raisonnements *échouent.*"],
         leyenda="Ton corps aussi a besoin d'être rassuré, pas seulement ta tête. 🤲"),
    # 32
    dict(n=100, hook="Tu es bien plus vaste\nque la somme\nde tes *peurs*.",
         texto=["L'anxiété réduit ton identité à un état de stress.",
                "Mais tu es une personne pleine de talents, de désirs et de force.",
                "Ne laisse pas l'alarme de ta maison en devenir l'unique habitante.",
                "Tu es le propriétaire. Pas le système de *sécurité.*"],
         leyenda="Ta peur fait partie de toi, mais elle n'est pas toi. 🏡"),
    # 33
    dict(n=46, hook="Une belle journée,\nune seule remarque…\net c'est elle\nque tu *retiens*.",
         texto=["Ton esprit agit comme un tamis qui ne garderait que les cailloux pointus.",
                "Tout ce qui va bien passe à travers. Seule la menace reste.",
                "Réapprendre à voir ce qui va bien, ce n'est pas de la naïveté.",
                "C'est de la rééducation *neurologique.*"],
         leyenda="Ce soir, cherche trois choses qui sont allées bien aujourd'hui. ✨"),
    # 34
    dict(n=70, hook="Ton système nerveux\nn'est pas fait pour\nse calmer *seul*.",
         texto=["Nous sommes des êtres sociaux.",
                "Le simple fait de savoir que tu as quelqu'un à qui parler apaise ton corps.",
                "L'isolement n'est pas de l'autonomie. C'est une charge que ton organisme n'est pas fait pour porter.",
                "Avoir besoin des autres n'est pas une faiblesse. C'est un acte de *santé.*"],
         leyenda="Envoie un message à quelqu'un aujourd'hui, même un tout petit. 💬"),
    # 35
    dict(n=10, hook="« Si je m'arrête,\ntout s'effondre. »\nTon corps est resté\nsur ce *réglage*.",
         texto=["Si on a attendu de toi, très tôt, que tu sois responsable, tu as appris à porter le monde sur tes épaules.",
                "Ton corps n'a jamais quitté ce réglage.",
                "Alors il ne s'arrête jamais vraiment.",
                "Déléguer, lâcher prise, dire « je ne sais pas » : ce n'est pas démissionner. C'est te *libérer.*"],
         leyenda="Le monde ne repose pas sur tes seules épaules. 🌍"),
    # 36
    dict(n=69, hook="N'attends pas que\nla peur parte pour\n*commencer*.",
         texto=["Attendre que l'anxiété disparaisse avant de faire ce qui compte, c'est le meilleur moyen de ne jamais commencer.",
                "Le courage, ce n'est pas l'absence de peur. C'est agir avec elle.",
                "C'est en agissant malgré l'angoisse que ton cerveau découvre qu'il avait surestimé le danger.",
                "La confiance ne vient pas avant l'action. Elle en est la *récompense.*"],
         leyenda="Un pas imparfait vaut mieux que mille attentes parfaites. 🚶"),
    # 37
    dict(n=24, hook="Mal sans savoir\npourquoi ? Ton corps\na vu quelque chose\n*avant* toi.",
         texto=["Ton système nerveux capte les signaux de danger avant même que ta pensée ait compris la situation.",
                "On appelle ça la neuroception.",
                "Si tu te sens mal sans raison apparente, ton corps a peut-être remarqué quelque chose que tu n'as pas encore traité.",
                "Ne cherche pas tout de suite une explication. Commence par rassurer ton *corps.*"],
         leyenda="Pas besoin de tout comprendre pour prendre soin de toi. 🌾"),
    # 38
    dict(n=51, hook="Tu compares\ntes coulisses avec\nleur vitrine. C'est\n*déloyal*.",
         texto=["Tu compares tes doutes, tes peurs, ton envers du décor, avec le décor bien poli des autres.",
                "Évidemment, tu perds à chaque fois.",
                "Chacun porte un fardeau invisible.",
                "La seule personne à qui te comparer, c'est celle que tu étais *hier.*"],
         leyenda="Derrière chaque vitrine, il y a des coulisses en désordre. 🎭"),
    # 39
    dict(n=52, hook="Ton indécision ?\nSouvent de la peur\ndéguisée en *analyse*.",
         texto=["Tu penses qu'en réfléchissant plus longtemps, tu finiras par faire le choix parfait.",
                "Mais rester au milieu du carrefour est le choix qui te coûte le plus d'énergie.",
                "Choisis. Agis. Ajuste ensuite.",
                "Le mouvement apaise l'*incertitude.*"],
         leyenda="Il n'y a pas de choix parfait, seulement des choix que l'on ajuste. 🔀"),
    # 40
    dict(n=80, hook="Ton anxiété est\nun circuit appris.\nTu peux en tracer\nun *autre*.",
         texto=["Chaque fois que tu évites, rumines ou vérifies, tu renforces un chemin dans ton cerveau.",
                "Le cerveau répète ce qu'il pratique. Mais ça marche dans les deux sens.",
                "Chaque fois que tu restes, que tu ne vérifies pas, que tu respires au lieu de fuir, tu construis un nouveau circuit.",
                "C'est lent. Mais c'est *réel.*"],
         leyenda="Chaque petit choix compte, même quand tu ne vois pas encore la différence. 🧩"),
    # 41
    dict(n=39, hook="Ruminer, c'est chercher\nla sortie d'un labyrinthe\nqui n'a pas de *murs*.",
         texto=["On croit qu'à force d'y penser, on finira par trouver la solution.",
                "Mais la rumination n'est pas de la réflexion. C'est une boucle fermée.",
                "Elle ne cherche pas de solution. Elle essaie d'éviter l'inconfort de l'incertitude.",
                "La sortie n'est pas dans ta tête. Elle est dans l'*action.*"],
         leyenda="Quand tes pensées tournent en rond, fais un pas, n'importe lequel. 🔄"),
    # 42
    dict(n=72, hook="Tu ajustes tes mots,\ntes émotions, tes gestes…\npour qu'on t'*accepte* ?",
         texto=["Faire plaisir à tout prix est une réponse de survie : tu essaies d'éviter le rejet en étant irréprochable.",
                "Tu ajustes tout pour mériter l'approbation des autres.",
                "Mais cette vigilance constante t'épuise.",
                "Tu as le droit d'être en sécurité même dans le désaccord. Même quand tu *déçois.*"],
         leyenda="Tu n'as pas besoin d'être irréprochable pour mériter ta place. 🌷"),
    # 43
    dict(n=11, hook="Le perfectionnisme\nest une armure\ncontre le *rejet*.",
         texto=["Tu penses que si tu es irréprochable, personne ne pourra te rejeter, te critiquer ou te faire mal.",
                "Mais cette armure est devenue si lourde qu'elle t'empêche de respirer.",
                "Et de te relier aux autres.",
                "La vraie connexion ne passe pas par la perfection. Elle passe par les *fissures.*"],
         leyenda="Tes imperfections ne t'éloignent pas des autres, elles t'en rapprochent. 🫧"),
    # 44
    dict(n=95, hook="Fais une place\nà ta peur. Mais garde\nles mains sur\nle *volant*.",
         texto=["Ta peur n'a pas besoin de disparaître pour que tu avances.",
                "Le courage, c'est l'action menée avec la peur à tes côtés.",
                "Attendre de ne plus avoir peur pour vivre, c'est le meilleur moyen de passer à côté de ta vie.",
                "Laisse-lui le siège passager. Mais c'est toi qui *conduis.*"],
         leyenda="Elle peut venir avec toi, mais elle ne choisit pas la route. 🚗"),
    # 45
    dict(n=42, hook="« Si ce n'est pas\nparfait, j'ai tout\n*raté*. »",
         texto=["La pensée « tout ou rien » ne voit que deux cases : parfait, ou échec.",
                "Elle ignore toutes les nuances, alors que c'est là que se trouve la vie.",
                "Chaque imperfection devient une alerte.",
                "Apprendre à vivre dans le gris, c'est offrir un peu de repos à ton système *nerveux.*"],
         leyenda="Entre parfait et raté, il y a tout le reste, et c'est déjà beaucoup. 🎨"),
    # 46
    dict(n=99, hook="Le futur ne se gère pas\nd'un seul coup.\nUne minute à la *fois*.",
         texto=["L'anxiété essaie de résoudre les problèmes de l'année prochaine avec tes ressources d'aujourd'hui.",
                "C'est impossible. Et c'est épuisant.",
                "Ton seul travail, maintenant, c'est de traverser l'heure qui vient.",
                "Pour le reste, tu auras ce qu'il faut le moment *venu.*"],
         leyenda="Juste l'heure qui vient, rien de plus. ⏱️"),
    # 47
    dict(n=66, hook="Le calme te paraît\nsuspect ? C'est que tu\nas vécu dans le *chaos*.",
         texto=["Quand l'anxiété s'apaise enfin, tu peux ressentir un drôle de malaise.",
                "Ton système nerveux a fait de l'alerte sa zone de confort.",
                "Le calme lui semble louche, comme si tu baissais la garde avant une attaque.",
                "Il doit réapprendre que le silence n'est pas un danger. C'est un repos *mérité.*"],
         leyenda="Laisse au calme le temps de devenir familier. 🕯️"),
    # 48
    dict(n=4, hook="Ta réaction est\ndisproportionnée ?\nC'est peut-être\nun *écho*.",
         texto=["Parfois, ton corps réagit à une situation présente avec une intensité qui te dépasse.",
                "Ce n'est pas une réaction au « maintenant ». C'est un écho d'« hier ».",
                "Ton système nerveux n'a pas fini de digérer une ancienne blessure.",
                "Le traiter avec douceur, c'est l'aider à comprendre qu'il est enfin en *sécurité.*"],
         leyenda="Ce n'est pas toi qui exagères, c'est hier qui parle fort. 🔁"),
    # 49
    dict(n=28, hook="Ton ventre est\nton deuxième cerveau\n*émotionnel*.",
         texto=["Ton système digestif est intimement lié à ton état nerveux.",
                "Quand l'anxiété monte, ton corps détourne l'énergie de la digestion vers les muscles de survie. D'où ce nœud.",
                "Prendre soin de ton ventre, c'est aussi parler à ton cerveau.",
                "Une respiration qui descend jusqu'au ventre lui envoie un message de *sécurité.*"],
         leyenda="Ton ventre ressent souvent avant que tu comprennes. 🍵"),
    # 50
    dict(n=58, hook="Penser à une chose\nhorrible ne la fait pas\n*arriver*.",
         texto=["Ton anxiété essaie de te faire croire que tes pensées ont un pouvoir : provoquer le pire, ou faire de toi une mauvaise personne.",
                "C'est faux.",
                "Une pensée est un événement dans ton cerveau. Pas un sortilège. Pas une intention. Pas une prédiction.",
                "Tu peux avoir les pensées les plus sombres sans qu'elles changent la réalité d'un *millimètre.*"],
         leyenda="Une pensée qui fait peur n'est qu'un bruit, pas un présage. 🌑"),
    # 51
    dict(n=6, hook="Ta peur d'échouer\ncache souvent la peur\nde perdre ta *place*.",
         texto=["L'anxiété de performance n'a souvent rien à voir avec le travail lui-même.",
                "Tu as peut-être appris très tôt que ta valeur dépendait de tes résultats, ou de ta capacité à ne poser aucun problème.",
                "Alors tu crois qu'en échouant, tu perdrais ta place dans le cœur des autres.",
                "Mais ta valeur ne se mérite pas. Tu es une personne, pas un *rendement.*"],
         leyenda="Tu comptes pour ce que tu es, pas pour ce que tu produis. 🌻"),
    # 52
    dict(n=90, hook="Plus tu luttes contre\nton angoisse, plus elle\ns'*accroche*.",
         texto=["Chaque fois que tu te bats contre une sensation ou une pensée, tu envoies un signal d'urgence à ton cerveau.",
                "Il en conclut que l'anxiété elle-même est un danger.",
                "Et il renforce l'alerte.",
                "Arrêter de te battre, c'est couper le carburant de l'*angoisse.*"],
         leyenda="Et si, pour une fois, tu arrêtais de te battre ? 🏳️"),
    # 53
    dict(n=16, hook="Ta peur de décevoir\nest plus forte que\nta peur d'*échouer* ?",
         texto=["Tu es capable de réussir. Mais l'idée de ne pas répondre aux attentes des autres te paralyse.",
                "Que ces attentes soient réelles ou imaginées, le poids est le même.",
                "Ce fardeau, tu n'as pas à le porter.",
                "Tu as le droit de décevoir pour rester fidèle à *toi-même.*"],
         leyenda="Décevoir quelqu'un ne fait pas de toi quelqu'un de décevant. 💫"),
    # 54
    dict(n=64, hook="Tu peux écouter\nce que ton cerveau dit…\nsans lui *obéir*.",
         texto=["Ton anxiété te fait croire que tes pensées t'enferment.",
                "En réalité, tu es celle ou celui qui les observe.",
                "Entre une pensée et ta réaction, il existe un espace invisible. C'est là que se trouve ta liberté.",
                "Rien ne t'oblige à croire tout ce que ton cerveau *raconte.*"],
         leyenda="Une pensée peut frapper à la porte sans que tu lui ouvres. 🗝️"),
    # 55
    dict(n=53, hook="T'inquiéter ne protège\nde rien. Ça gâche\njuste le *trajet*.",
         texto=["Ton anxiété te fait croire qu'en t'inquiétant assez, tu pourras éviter la douleur.",
                "Mais l'inquiétude n'a aucun pouvoir sur les événements.",
                "Elle ne change pas l'issue.",
                "La vraie préparation, ce n'est pas la rumination. C'est ta stabilité *intérieure.*"],
         leyenda="Tu peux arriver au même endroit en profitant un peu plus du chemin. 🌄"),
    # 56
    dict(n=93, hook="Écrire tes peurs\nles fait passer\nde l'émotion\nà la *raison*.",
         texto=["Ton cerveau ne peut pas à la fois vivre une émotion brute et la transformer en phrases.",
                "Poser tes mots sur le papier oblige tes pensées à s'aligner, et à sortir de ton corps.",
                "Ce qui reste enfermé grossit. Ce qui est posé sur le papier perd de sa charge.",
                "Un stylo, une feuille, cinq minutes. C'est *tout.*"],
         leyenda="Ce soir, essaie d'écrire tout ce qui tourne dans ta tête, sans filtre. ✍️"),
    # 57
    dict(n=13, hook="Mal à l'aise en groupe ?\nTon alarme surveille\nle *regard* des autres.",
         texto=["Ce n'est pas un manque de sociabilité.",
                "Ton système de détection des menaces s'est branché sur le regard des autres, parce que tu as appris que le jugement pouvait faire mal.",
                "Ta vigilance est un bouclier contre un rejet que tu imagines insupportable.",
                "Mais la plupart des gens sont bien trop occupés par leur propre anxiété pour te *juger.*"],
         leyenda="Les autres pensent beaucoup moins à toi que tu ne le crois, et c'est une bonne nouvelle. 😌"),
    # 58
    dict(n=68, hook="L'auto-compassion\nn'est pas de la\ncomplaisance.\nC'est un *réglage*.",
         texto=["Te parler avec douceur en pleine crise, ce n'est pas te laisser aller.",
                "C'est envoyer à ton cerveau un message clair : « Tu es en sécurité, même dans l'inconfort. »",
                "La dureté envers toi-même ne fait qu'ajouter du stress au stress.",
                "La douceur n'enlève rien à ta force. Elle t'aide à *tenir.*"],
         leyenda="Sois de ton côté, surtout dans les moments difficiles. 🫂"),
    # 59
    dict(n=45, hook="« Je suis comme ça. »\nCette phrase t'empêche\nde *changer*.",
         texto=["« C'est ma nature. » « J'ai toujours été comme ça. »",
                "Quand tu transformes un état passager en identité, tu fermes la porte au changement.",
                "Ton cerveau, lui, reste capable d'évoluer.",
                "Une étiquette est une prison. L'observation est une *libération.*"],
         leyenda="Tu n'es pas ton anxiété, tu traverses une période. 🦋"),
    # 60
    dict(n=9, hook="Tu stresses pour\ndes détails ? Tu portes\nun poids *invisible*.",
         texto=["Tu te sens souvent moins capable que les autres, parce que tu t'inquiètes pour des choses qu'ils semblent ignorer.",
                "Mais regarde la réalité : tu mènes tes journées avec un poids intérieur que beaucoup ne supporteraient pas une heure.",
                "Fonctionner malgré cette tempête, c'est une preuve de force.",
                "Tu n'es pas quelqu'un d'incompétent. Tu joues simplement en mode *difficile.*"],
         leyenda="Ce que tu accomplis compte double, même si personne ne voit le poids que tu portes. 🎒"),
    # 61
    dict(n=47, hook="« J'ai raté une fois,\ndonc je raterai\n*toujours*. »",
         texto=["C'est une erreur de calcul.",
                "Ton cerveau cherche des règles là où il n'y a que des expériences isolées.",
                "Chaque moment est une nouvelle occasion, indépendante du passé.",
                "Une erreur d'hier ne prédit pas ton *demain.*"],
         leyenda="Hier n'écrit pas demain à ta place. 📝"),
    # 62
    dict(n=48, hook="Quelqu'un est de mauvaise\nhumeur et tu te demandes\nce que tu as *fait* ?",
         texto=["C'est souvent ton premier réflexe : chercher ce que tu as fait de mal.",
                "Mais les réactions des autres parlent d'eux.",
                "De leur sommeil, de leur propre stress, de leur journée.",
                "Et presque jamais de *toi.*"],
         leyenda="Tout ne te concerne pas, et c'est plutôt reposant. ☕"),
    # 63
    dict(n=23, hook="Ton anxiété adore\njouer au *médecin*.",
         texto=["Elle te fait croire qu'un vertige ou un picotement annonce forcément quelque chose de grave.",
                "Pourtant, ton corps réagit souvent à tes pensées, pas à une panne.",
                "Écoute tes sensations sans leur donner un pouvoir de prophétie.",
                "En cas de doute, un vrai médecin peut vérifier. Ton anxiété, elle, n'a pas de *diplôme.*"],
         leyenda="Prends soin de ton corps, sans laisser ton anxiété faire le diagnostic. 🩺"),
    # 64
    dict(n=91, hook="L'accueillir n'est pas\nabandonner.\nC'est une *stratégie*.",
         texto=["Dès que tu acceptes sa présence, ton système nerveux commence à se détendre.",
                "« D'accord. L'anxiété est là, en ce moment. »",
                "Accepter ne veut pas dire aimer.",
                "Cela veut dire arrêter de te battre contre la vague, pour commencer à *flotter.*"],
         leyenda="Tu n'as pas à l'aimer, seulement à arrêter de lutter. 🏊"),
    # 65
    dict(n=34, hook="Une marche de dix\nminutes peut calmer\nune tempête *intérieure*.",
         texto=["Quand l'anxiété monte, parler à ton cerveau ne suffit pas toujours.",
                "Marcher, danser, secouer les bras, étirer le dos envoie un message direct à ton système nerveux : « Je bouge, le danger ne me tient pas. »",
                "Le mouvement libère l'adrénaline accumulée et aide ton corps à boucler le cycle du stress.",
                "Ne sous-estime jamais une simple *marche.*"],
         leyenda="Si tu peux, sors marcher dix minutes aujourd'hui. 👟"),
    # 66
    dict(n=75, hook="Ce que les autres\npensent de toi parle\nd'*eux*.",
         texto=["Les gens te jugent à travers le filtre de leurs propres peurs, de leur fatigue, de leur histoire.",
                "Leur regard est un bruit de fond, pas une vérité absolue.",
                "Si ta sécurité intérieure dépend de leur avis, un simple froncement de sourcils suffira à te faire vaciller.",
                "L'approbation qui compte vraiment, c'est la *tienne.*"],
         leyenda="Ton avis sur toi mérite plus de place que le leur. 🪞"),
    # 67
    dict(n=36, hook="Tout planifier ? C'est\nton système nerveux\nqui réclame de la\n*sécurité*.",
         texto=["Tu passes une énergie énorme à tout prévoir pour éviter l'imprévu.",
                "Anticiper, c'est tenter de contrôler. Contrôler, c'est chercher la sécurité.",
                "Mais la sécurité ne se trouve pas dans l'agenda.",
                "La vraie sécurité, c'est la capacité de traverser l'imprévu sans t'*effondrer.*"],
         leyenda="Tu as déjà traversé des imprévus, et tu sais faire plus que tu ne le crois. 📅"),
    # 68
    dict(n=None, hook="L'anxiété ne s'apaise\npas quand on la\ncombat. Mais quand\non l'*accueille*.",
         texto=["Je ne suis ni psychologue, ni thérapeute.",
                "J'ai vécu des années avec l'anxiété. J'ai tout essayé : la méditation, la thérapie, les livres, les applis, la respiration, le yoga.",
                "Et j'ai fini par comprendre une chose simple.",
                "Je ne promets pas de miracle. Je propose un *chemin.*"],
         leyenda="Ce livre est né d'un parcours, pas d'une théorie. 🪴"),
    # 69
    dict(n=27, hook="Tu ne tiens pas\nen place ? C'est de\nl'énergie qui cherche\nune *sortie*.",
         texto=["Cette envie de bouger, de tapoter, cette impatience nerveuse : c'est un surplus d'adrénaline.",
                "Essayer de rester immobile ne fait souvent qu'augmenter la tension.",
                "Alors bouge. Marche, secoue tes mains, danse.",
                "Utilise cette énergie pour ce qu'elle est : un moteur qui demande à *tourner.*"],
         leyenda="Ton agitation n'est pas un défaut, c'est de l'énergie en trop. ⚡"),
    # 70
    dict(n=77, hook="Ta valeur ne se mesure\npas à ton *utilité*.",
         texto=["Tu crois peut-être que tu n'as de valeur que si tu es utile, efficace, indispensable.",
                "Alors tu en fais toujours plus, pour avoir le droit de prendre de la place.",
                "Mais tu es une personne, pas un outil.",
                "Ton droit à l'amour et au repos ne dépend pas de ta liste de *tâches.*"],
         leyenda="Tu as le droit d'exister sans rien prouver. 🌼"),
    # 71
    dict(n=54, hook="Ton cerveau retient\nles échecs pour te\n*protéger*.",
         texto=["Ton anxiété du moment colore tes souvenirs.",
                "Les ratés restent gravés. Les réussites s'effacent.",
                "Pour rééquilibrer, note tes petites victoires, chaque jour.",
                "Ton cerveau a besoin de preuves écrites pour croire que tout ne va pas si *mal.*"],
         leyenda="Quelle petite victoire pourrais-tu noter aujourd'hui ? 🏅"),
    # 72
    dict(n=5, hook="Ton passé ne disparaît\npas. Il s'imprime dans\nton système *nerveux*.",
         texto=["Des tensions chroniques, des sursauts au moindre bruit, une fatigue inexpliquée…",
                "Ce sont parfois les empreintes de ton histoire.",
                "C'est pour ça qu'on ne s'apaise pas seulement par la pensée, mais aussi par le corps.",
                "Ton corps a besoin de réapprendre, physiquement, que le danger est *terminé.*"],
         leyenda="Ton corps se souvient, et il peut aussi apprendre autre chose. 🍂"),
    # 73
    dict(n=62, hook="Une erreur n'est pas\nune condamnation.\nC'est une *donnée*.",
         texto=["Ton anxiété redoute l'erreur comme si elle était fatale.",
                "Pourtant, l'erreur est le seul vrai chemin pour apprendre.",
                "Ton système nerveux grandit dans les ajustements, pas dans la performance rigide.",
                "Une erreur ne dit rien de ta valeur. Juste qu'il faut pratiquer encore un *peu.*"],
         leyenda="Rater fait partie d'apprendre, pour tout le monde. 📊"),
    # 74
    dict(n=71, hook="La honte grandit\ndans le secret.\nElle s'éteint dans\nla *parole*.",
         texto=["L'anxiété se nourrit souvent de la honte de « ne pas être normal ».",
                "Tant que tu caches tes peurs, elles gardent leur pouvoir sur toi.",
                "En osant dire « je ne vais pas bien en ce moment », tu découvres que beaucoup traversent les mêmes tempêtes.",
                "La vulnérabilité partagée est le plus puissant antidote à l'*isolement.*"],
         leyenda="Dire « ça ne va pas », c'est déjà un acte de courage. 🗣️"),
    # 75
    dict(n=33, hook="Ralentir n'est pas\nperdre du temps.\nC'est gagner\nen *clarté*.",
         texto=["Dans la précipitation et l'urgence, ton regard se rétrécit sur la menace.",
                "Tu ne vois plus qu'elle.",
                "En ralentissant tes gestes et ton rythme, tu permets à ton système nerveux de sortir du mode survie.",
                "Et de retrouver une vision d'ensemble, avec des solutions *réelles.*"],
         leyenda="Ralentis un seul geste aujourd'hui, juste un. 🐢"),
    # 76
    dict(n=98, hook="Ton anxiété te montre\nles endroits où tu ne\nte respectes *plus*.",
         texto=["Elle n'est pas là pour t'embêter.",
                "Elle signale les zones de friction : là où tu ne te respectes plus, là où tes valeurs sont bafouées.",
                "Parfois, là où un changement est devenu nécessaire.",
                "Écoute le message caché derrière le bruit de l'*alarme.*"],
         leyenda="Et si ton anxiété avait raison sur un point ? 🔍"),
    # 77
    dict(n=7, hook="Ton besoin de tout\nprévoir est né d'une\npériode *imprévisible*.",
         texto=["Si tu as grandi là où les humeurs et les événements changeaient sans prévenir, ton cerveau a choisi la vigilance pour survivre.",
                "Ce besoin de tout prévoir est le reste d'un mécanisme qui a été utile autrefois.",
                "Ce n'est pas un défaut de caractère.",
                "C'est la preuve de ta capacité d'*adaptation.*"],
         leyenda="Tu as appris à t'adapter au chaos, tu peux maintenant apprendre le calme. 🌈"),
    # 78
    dict(n=81, hook="Arrête de deviner\nce que les autres\n*pensent*.",
         texto=["Tu crois lire dans leurs pensées. En réalité, tu projettes tes propres peurs sur leur visage.",
                "Ce que tu crois voir chez eux, c'est souvent ton propre dialogue intérieur.",
                "Les gens sont bien trop occupés par leur propre petite voix pour te juger autant que tu le crois.",
                "Arrête de deviner. Reste là, avec eux, *maintenant.*"],
         leyenda="Tu n'es pas dans leur tête, et c'est très bien comme ça. 💭"),
    # 79
    dict(n=63, hook="Tu regardes le film\nde ta vie au lieu\nd'y *jouer*.",
         texto=["L'anxiété te fait passer plus de temps à analyser ce que tu ressens qu'à le ressentir vraiment.",
                "Tu vis dans ta tête, loin de ta propre vie.",
                "Revenir à tes cinq sens, au toucher, au goût, au mouvement, c'est sortir de la simulation.",
                "Et retrouver le goût du *réel.*"],
         leyenda="Qu'est-ce que tu peux sentir, entendre ou toucher, là, maintenant ? 🎬"),
    # 80
    dict(n=18, hook="La perfection\nn'apporte pas la paix.\nElle l'*empêche*.",
         texto=["Tu crois que l'anxiété partira quand tout sera enfin réglé : le travail idéal, la maison idéale, la relation idéale.",
                "Mais la vie est un mouvement perpétuel d'imprévus.",
                "Chercher la paix dans la perfection, c'est une quête sans fin.",
                "La vraie sécurité, c'est d'apprendre à être en paix au milieu du *désordre.*"],
         leyenda="Rien ne sera jamais parfaitement réglé, et tu peux quand même aller bien. 🍀"),
    # 81
    dict(n=44, hook="« Je devrais… »\n« Il faudrait… »\nDes chaînes\n*invisibles*.",
         texto=["Chaque « je devrais » dit à ton cerveau que tu n'es pas assez, comme tu es.",
                "C'est une pression de plus, jour après jour.",
                "Remplace-les par « j'aimerais » ou « je choisis de ».",
                "Ces mots te rendent ton pouvoir, et font baisser la *tension.*"],
         leyenda="Essaie aujourd'hui un « je choisis de » à la place d'un « je devrais ». 🔗"),
    # 82
    dict(n=89, hook="Ton anxiété est\nune énergie qui cherche\nun *canal*.",
         texto=["L'anxiété, c'est une quantité énorme d'énergie mentale.",
                "Aujourd'hui, elle tourne en boucle contre toi.",
                "Mais redirigée vers la création, le mouvement ou l'action, elle peut devenir ton carburant le plus puissant.",
                "Ce n'est pas une faille. C'est une force qui attend sa *direction.*"],
         leyenda="Et si tu donnais à cette énergie quelque chose à construire ? 🔥"),
    # 83
    dict(n=86, hook="Tes peurs dans\ntes relations viennent\nsouvent de *loin*.",
         texto=["L'anxiété dans les relations vient souvent d'un besoin de sécurité qui n'a pas été comblé dans le passé.",
                "Tes peurs d'aujourd'hui sont parfois les échos de tes besoins d'enfant.",
                "Le comprendre permet d'arrêter d'en vouloir à ton partenaire ou à tes amis.",
                "Et de rassurer, toi-même, la part de toi qui craint l'*abandon.*"],
         leyenda="Cette part de toi qui a peur a d'abord besoin de toi. 🧸"),
    # 84
    dict(n=None, hook="Comprendre est\nun début. Pratiquer\nest le vrai *tournant*.",
         texto=["La connaissance seule ne calme pas un système nerveux en alerte.",
                "Il apprend par répétition, pas par lecture.",
                "Une respiration consciente. Un regard bienveillant sur ta journée. Quelques lignes écrites le soir.",
                "Comprendre est un premier pas. La pratique fait le *reste.*"],
         leyenda="Tu as déjà les clés, et tu peux commencer dès aujourd'hui. 🔑"),
    # 85
    dict(n=49, hook="« C'était juste\nde la *chance*. »\nEt si c'était toi ?",
         texto=["Quand une bonne chose arrive, tu trouves toujours une raison pour qu'elle ne compte pas.",
                "Résultat : ton système nerveux n'enregistre jamais de preuves de sécurité.",
                "Il ne garde que les alertes.",
                "Accepte les compliments et les réussites comme de vraies *données.*"],
         leyenda="La prochaine fois qu'on te fait un compliment, dis juste « merci ». 🎁"),
    # 86
    dict(n=74, hook="Tu n'es pas\nle régulateur émotionnel\ndu *monde*.",
         texto=["L'hyper-empathie peut devenir une prison.",
                "Si tu te sens responsable du bonheur de tout ton entourage, ton système nerveux reste en alerte permanente.",
                "Tu peux être là pour les autres sans absorber leur douleur.",
                "Prendre soin d'eux, oui. Porter leurs émotions à leur place, *non.*"],
         leyenda="Tu peux tenir la main de quelqu'un sans porter tout son poids. 🧡"),
    # 87
    dict(n=60, hook="Le contrôle est une\nprison dont les barreaux\nsont tes *inquiétudes*.",
         texto=["Plus tu essaies de tout maîtriser, les pensées des autres, le futur, ta santé, plus l'impuissance grandit, parce que l'essentiel t'échappe.",
                "Ton anxiété se nourrit de cette quête impossible.",
                "Lâcher prise, ce n'est pas abandonner.",
                "C'est arrêter de gaspiller ton énergie là où tu n'as aucun pouvoir, pour la mettre là où tu peux *agir.*"],
         leyenda="Commence par ce qui dépend vraiment de toi aujourd'hui. 🎯"),
    # 88
    dict(n=30, hook="Ton anxiété veut\ndu confort. Tu as\nbesoin de *sécurité*.",
         texto=["Le confort, c'est rester dans ce que tu connais.",
                "La sécurité, c'est savoir que tu peux faire face à l'inconnu.",
                "Ton anxiété réclame du confort.",
                "Ce dont tu as vraiment besoin, c'est de la certitude que, quoi qu'il arrive, tu t'en *sortiras.*"],
         leyenda="Quoi qu'il arrive, tu trouveras un chemin. 🛟"),
    # 89
    dict(n=92, hook="La sécurité intérieure\nse construit brique\npar *brique*.",
         texto=["Ce n'est pas un déclic soudain.",
                "C'est le résultat de petits choix répétés : respecter tes besoins, t'entourer de personnes bienveillantes, te parler avec douceur.",
                "Jour après jour.",
                "Une structure patiente, que tu bâtis toi-même, à ton *rythme.*"],
         leyenda="Quelle brique poses-tu aujourd'hui ? 🧱"),
    # 90
    dict(n=87, hook="Choisir ta paix\nplutôt que ton image :\nc'est là que tout\n*change*.",
         texto=["Il y a un moment où tu décides que ton calme intérieur compte plus que la façade que tu montres au monde.",
                "Ce choix demande du courage.",
                "Il implique de renoncer à contrôler ce que les autres pensent de toi.",
                "Et c'est précisément là que l'apaisement *commence.*"],
         leyenda="Ton calme vaut plus que leur approbation. 💙"),
    # 91
    dict(n=82, hook="Les gens s'attachent\nà ton humanité.\nPas à ton *masque*.",
         texto=["Tu passes ta vie à essayer d'être « assez » : à la hauteur, efficace, irréprochable.",
                "Mais personne ne s'attache à une façade parfaite.",
                "On s'attache à tes maladresses, à tes rires spontanés, à tes doutes partagés.",
                "Ce que tu caches, c'est souvent ce qu'on aime le plus chez *toi.*"],
         leyenda="Les bonnes personnes ne restent pas pour le masque. 💞"),
    # 92
    dict(n=None, hook="Ton corps ne\nte trahit pas.\nIl essaie de\nt'*alerter*.",
         texto=["L'anxiété est d'abord une expérience physique.",
                "Ton système nerveux mobilise ton énergie pour une survie que ton cerveau croit nécessaire.",
                "Palpitations, tensions, souffle court : ce sont les seuls outils qu'il possède pour te parler.",
                "Apprendre à les traduire, c'est transformer tes alarmes en signaux de *sécurité.*"],
         leyenda="Ton corps te parle avec les seuls mots qu'il connaît. 🫀"),
    # 93
    dict(n=78, hook="L'isolement est\nle festin de\nton *anxiété*.",
         texto=["Quand l'anxiété monte, on a tendance à se replier pour se protéger.",
                "C'est un piège.",
                "C'est dans la solitude que les pensées deviennent les plus féroces.",
                "Reprendre contact, même un tout petit peu, rappelle à ton cerveau que le monde contient aussi du soutien et de la *chaleur.*"],
         leyenda="Un message, un appel, un café : le lien fait du bien. 📞"),
    # 94
    dict(n=None, hook="Une voix crie au danger\nalors que tu prépares\njuste un *café* ?",
         texto=["Tu connais ce rythme trop rapide du cœur, ces doigts qui tremblent un peu.",
                "Cette impression d'avoir dans la tête un passager clandestin qui hurle au danger, alors que tu essaies juste de t'endormir.",
                "On t'a dit que c'était une erreur de fabrication, quelque chose à « gérer » comme une fuite d'eau.",
                "Et si c'était une part de toi qui essayait, maladroitement, de te *protéger* ?"],
         leyenda="Tu n'es pas la seule personne à vivre ça, loin de là. 🤗"),
    # 95
    dict(n=None, hook="Avant de dormir :\ncinq minutes pour\nvider ta *tête*.",
         texto=["Prends une feuille, et écris tout ce qui tourne dans ta tête.",
                "Sans filtre. Sans structure. Sans te relire.",
                "Vide le mental sur le papier.",
                "Ton cerveau dort mieux quand il n'a plus à retenir tes *inquiétudes.*"],
         leyenda="Ce soir, essaie, juste cinq minutes. 📓"),
    # 96
    dict(n=None, hook="Le bon moment\npour commencer ne\nviendra pas *seul*.",
         texto=["Tu ne te sentiras peut-être jamais tout à fait à la hauteur pour commencer.",
                "C'est en commençant qu'on devient capable.",
                "Ces vérités ne vivent vraiment que si tu les pratiques.",
                "Tu as plus de force que tu ne le crois. Et tu peux commencer *aujourd'hui.*"],
         leyenda="Tu as plus de force que tu ne l'imagines, depuis le début. 💪"),
    # 97
    dict(n=None, hook="Tu ne peux pas écrire\naussi vite que tu penses.\nEt c'est *précieux*.",
         texto=["Quand tu écris, ton cerveau est obligé de ralentir.",
                "Tes émotions sortent de ton corps pour se poser sur le papier.",
                "Et une distance se crée entre toi et ce que tu ressens.",
                "Ce qui tournait en boucle devient enfin *lisible.*"],
         leyenda="Une page blanche peut accueillir ce que ta tête ne peut plus porter. 🖊️"),
    # 98
    dict(n=85, hook="Une critique dit plus\nsur celui qui la fait\nque sur *toi*.",
         texto=["Quand quelqu'un te juge, il regarde le monde à travers ses propres douleurs et ses peurs non résolues.",
                "Ce qu'il voit en toi est souvent ce qu'il refuse de voir en lui-même.",
                "Sa critique peut te toucher. Elle ne te définit pas.",
                "Son jugement est son miroir. Pas ta *vérité.*"],
         leyenda="Ce qu'on dit de toi ne décide pas de qui tu es. 🛡️"),
    # 99
    dict(n=21, hook="Ton souffle court\nn'est pas un manque\nd'air. C'est une\n*armure*.",
         texto=["Quand l'anxiété monte, tu respires « haut », dans la poitrine.",
                "Ce n'est pas que l'air manque. C'est que tes muscles se contractent, prêts à l'effort.",
                "En allongeant doucement ton expiration, tu envoies un signal à ton cerveau.",
                "« Le danger est passé. On peut relâcher la *pression.* »"],
         leyenda="Expire un peu plus longtemps que tu n'inspires, et recommence. 🫁"),
    # 100
    dict(n=None, hook="On t'a appris à\nfaire taire ton anxiété.\nEt si elle avait quelque\nchose à te *dire* ?",
         texto=["Pendant longtemps, on t'a vendu des techniques pour l'étouffer, la contrôler, redevenir « comme tout le monde ».",
                "Mais on ne fait pas la guerre à une partie de soi.",
                "Ton anxiété est une part de toi qui a eu très peur, un jour, et qui n'a plus jamais baissé la garde.",
                "Derrière le bruit de l'alarme, il y a un message. Ce livre t'aide à le *traduire.*"],
         leyenda="Ton anxiété a quelque chose à te dire. 💌"),
    # 101
    dict(n=59, hook="Ton cerveau confond\n« je ne sais pas »\navec *catastrophe*.",
         texto=["Ton anxiété réclame des garanties à 100 %. Mais la vie ne fonctionne pas ainsi.",
                "Pour ton cerveau, l'inconfort du flou ressemble à un danger imminent.",
                "Pourtant, ne pas savoir, ce n'est pas être en danger.",
                "Rester avec le « je ne sais pas » sans chercher de réponse tout de suite est une compétence. Elle s'*apprend.*"],
         leyenda="Ne pas savoir n'est pas une menace, juste une question encore ouverte. ❔"),
    # 102
    dict(n=79, hook="Sur les réseaux,\ntout le monde a l'air\nde mieux *gérer*.",
         texto=["Tu regardes les autres et ils semblent tous mieux s'en sortir que toi.",
                "Mais tu compares tes doutes intérieurs avec leur façade publique.",
                "Tout le monde porte un fardeau invisible.",
                "Ton anxiété n'est pas une exception. C'est un trait profondément *humain.*"],
         leyenda="Personne ne publie ses nuits blanches. 📱"),
    # 103
    dict(n=84, hook="Tu cherches dehors\nce que tu n'oses pas\nencore te *donner*.",
         texto=["Ton besoin de validation cache souvent un doute ancien.",
                "Si ta sécurité dépend du sourire des autres, tu restes à la merci de leurs humeurs.",
                "La validation qui apaise vraiment, c'est celle que tu t'accordes.",
                "Ici, maintenant, sans condition de *réussite.*"],
         leyenda="Et si tu te disais, à toi, ce que tu attends d'entendre ? 🎙️"),
    # 104
    dict(n=None, hook="Comprendre.\nApaiser. Avancer.\nTe *retrouver*.",
         texto=["Comprendre l'alarme : pourquoi elle s'est mise en marche, et pourquoi tes réactions sont logiques.",
                "Habiter ton corps : traduire tes palpitations et tes tensions.",
                "Désamorcer les récits : sortir des scénarios catastrophes. Puis retrouver ta souveraineté.",
                "101 vérités, quatre actes, un seul but : faire la paix avec ton *anxiété.*"],
         leyenda="Un parcours en quatre actes, à ton rythme. 🧭"),
    # 105
    dict(n=76, hook="Montrer tes failles\nne t'affaiblit pas.\nÇa crée du *lien*.",
         texto=["On t'a appris que montrer tes failles était une faiblesse.",
                "Pourtant, c'est là que les liens se créent.",
                "Dire « je ne vais pas bien » ou « j'ai peur » ouvre un espace où l'autre peut déposer ses propres peurs.",
                "Les liens les plus profonds naissent quand quelqu'un ose baisser l'*armure.*"],
         leyenda="Ta vulnérabilité donne aux autres la permission d'être vrais. 🌸"),
    # 106
    dict(n=96, hook="Chaque petit pas\nmalgré l'angoisse est\nune *preuve*.",
         texto=["Tu attends peut-être de te sentir capable pour agir.",
                "Mais c'est l'action elle-même qui prouve à ton cerveau que tu en es capable.",
                "Chaque pas franchi malgré la peur est une preuve de sécurité qu'il enregistre.",
                "Pour la prochaine fois. Et celle d'*après.*"],
         leyenda="Chaque pas compte, surtout ceux qui t'ont coûté. 🪜"),
    # 107
    dict(n=57, hook="Ton attention ne voit\nque les dangers ? Elle\nest devenue *sélective*.",
         texto=["Quand l'anxiété est là, ton attention ne retient que les menaces possibles.",
                "Les signes de sécurité, eux, passent inaperçus.",
                "Si tout te semble aller mal, ton esprit cache ce qui va bien, pour ne pas contredire ce que tu ressens.",
                "Sortir de l'anxiété, c'est élargir doucement ton *regard.*"],
         leyenda="Regarde autour de toi : qu'est-ce qui va bien, même un peu ? 🔭"),
    # 108
    dict(n=None, hook="Il est trois heures\ndu matin. Ton cœur\nbat trop vite. Tu\nanticipes le *pire*.",
         texto=["Tes pensées tournent en boucle, et demain paraît déjà perdu.",
                "Ce n'est pas toi qui exagères. C'est une alarme qui sonne au mauvais moment.",
                "Elle ne sait pas encore que tu es en sécurité, là, dans ton lit.",
                "Mais toi, tu peux le lui *rappeler.*"],
         leyenda="La nuit grossit tout, le matin remet les choses à leur taille. 🌌"),
    # 109
    dict(n=41, hook="Tu crois lire\ndans leurs pensées ?\nC'est ta *peur* qui lit.",
         texto=["« Ils me trouvent ennuyeux. » « Ils me jugent. »",
                "Ces certitudes viennent rarement d'eux. Elles viennent de ton propre dialogue intérieur, projeté sur leur visage.",
                "Ton insécurité écrit le texte, puis le leur prête.",
                "La vérité est plus simple : les gens sont occupés par leurs propres *soucis.*"],
         leyenda="Ce que tu crois lire sur leur visage est souvent écrit par ta peur. 👀"),
    # 110
    dict(n=None, hook="Une pensée pèse moins\nlourd quand tu\nla *remarques*.",
         texto=["« Je suis cette pensée. » Ou bien : « Je remarque que j'ai la pensée que… »",
                "La différence a l'air minuscule.",
                "Pourtant, dans la deuxième phrase, une distance s'installe entre toi et ta peur.",
                "Et dans cette distance, tu peux enfin *respirer.*"],
         leyenda="Essaie la formule la prochaine fois qu'une pensée te happe. 🪶"),
    # 111
    dict(n=15, hook="Tu ne peux pas penser\nton apaisement.\nTu dois le *vivre*.",
         texto=["Tes tensions chroniques, tes douleurs mystérieuses, ta fatigue inexpliquée sont les archives de ton histoire émotionnelle.",
                "Les comprendre aide. Mais ça ne suffit pas.",
                "Le massage, le yoga, le mouvement doux parlent à ton corps dans sa propre langue.",
                "L'apaisement passe aussi par le *corps.*"],
         leyenda="Offre à ton corps un moment doux aujourd'hui. 🧘"),
    # 112
    dict(n=None, hook="Derrière le bruit\nde l'alarme, une voix\nqui te veut du *bien*.",
         texto=["Ton anxiété crie fort, maladroitement, à contretemps.",
                "Mais derrière ce vacarme, il y a une voix qui essaie de te dire que tu as de la valeur.",
                "Que ta vie mérite d'être protégée.",
                "Apprendre à l'écouter, c'est traduire ce vacarme en *sagesse.*"],
         leyenda="Tu n'es pas la seule personne dans ce brouillard. 🌁"),
    # 113
    dict(n=None, hook="Ton esprit est\nun maître de\nla *fiction*.",
         texto=["Il adore les scénarios « Et si… » et les prophéties de malheur.",
                "Il raconte des histoires si réalistes que ton corps y croit.",
                "Tu peux apprendre à observer tes pensées sans te confondre avec elles.",
                "Pour retrouver l'espace entre la peur et la *réalité.*"],
         leyenda="Ce que ton esprit raconte n'est pas toujours ce qui arrive. 📚"),
    # 114
    dict(n=19, hook="Toujours efficace,\ntoujours disponible…\net vide à l'*intérieur* ?",
         texto=["Tu aides tout le monde, tu es partout, tu ne lâches rien.",
                "Mais cette productivité est parfois une armure contre le rejet.",
                "Comme si tu devais être utile pour avoir le droit de prendre de la place.",
                "Tu as le droit de prendre de la place, même quand tu ne fais *rien.*"],
         leyenda="Ta place ne dépend pas de ta productivité. 🪑"),
    # 115
    dict(n=88, hook="Chaque vague que\ntu traverses te rend\nplus *solide*.",
         texto=["Les jours où l'anxiété revient, tu as l'impression que tout est à refaire.",
                "Pourtant, chaque vague traversée laisse une trace.",
                "Une preuve de plus que tu sais tenir debout dans la tempête.",
                "Tu ne recules pas. Tu renforces ta *résilience.*"],
         leyenda="Tu as déjà traversé chacune de tes pires journées. ⛵"),
    # 116
    dict(n=1, hook="Ton anxiété prouve\nque ton instinct de\nsurvie est *puissant*.",
         texto=["L'anxiété est la preuve physique de la puissance de ton instinct de survie.",
                "Ton cerveau est si performant pour détecter les menaces qu'il réagit parfois trop vite.",
                "Tu ne manques de rien. Tu as un équipement très sensible.",
                "Ton travail n'est pas de l'éteindre. C'est d'apprendre à le *calibrer.*"],
         leyenda="Un instinct aussi fort mérite d'être réglé, pas combattu. 🎛️"),
    # 117
    dict(n=None, hook="Ton cerveau n'a pas\nbesoin d'arguments.\nIl a besoin\nde *preuves*.",
         texto=["Comprendre d'où vient l'alarme ne suffit pas à l'éteindre.",
                "Ton cerveau a besoin de preuves concrètes, jour après jour, que tu es en sécurité maintenant.",
                "Ces preuves se construisent par de petits rituels : une respiration consciente, un regard bienveillant, quelques mots écrits.",
                "Ton système nerveux apprend par répétition. Pas par *lecture.*"],
         leyenda="Un petit rituel aujourd'hui, un autre demain. 🔂"),
    # 118
    dict(n=83, hook="Tes limites sont\nles murs porteurs\nde ta *paix*.",
         texto=["Dire « non » te semble cruel, parce qu'on t'a appris à prendre soin des autres avant toi.",
                "Mais tes limites n'ont rien d'égoïste.",
                "Elles empêchent ton système nerveux de s'effondrer sous le poids des attentes.",
                "Sans elles, rien ne tient *debout.*"],
         leyenda="Une maison sans murs porteurs ne tient pas longtemps, toi non plus. 🏠"),
    # 119
    dict(n=None, hook="Chaque soir, quelques\nlignes. Et tu écris\nla suite de ton\n*histoire*.",
         texto=["L'écriture est l'un des moyens les plus simples de calmer un système nerveux en alerte.",
                "En écrivant, tes pensées s'alignent en phrases et deviennent observables.",
                "Ce qui était flou devient clair. Ce qui était lourd devient plus léger.",
                "Page après page, c'est toi qui reprends la *plume.*"],
         leyenda="Quelques lignes ce soir, c'est déjà un début. 📔"),
    # 120
    dict(n=None, hook="Tes réactions ont\nune logique. Rien\nen toi n'est *cassé*.",
         texto=["Ton anxiété n'est pas une erreur système.",
                "C'est un mécanisme de protection, né à un moment où tout était imprévisible.",
                "Comprendre ça, c'est enfin arrêter de te voir comme un problème à réparer.",
                "Et commencer à faire la *paix.*"],
         leyenda="Tu n'as jamais été un problème à réparer. ☀️"),
]
